# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
